### ISSUE TITLE
Hour increment 

### ISSUE THREAD

**Issue by maaznadeem246** [muhammadAdeel6331/Assignment-8-Stopwatch-#1]
Hour is not being incremented in  app when minutes get value 60 so your hour should be incremented but it's not incrementing. your minute value crosses the 60 
Like 60 , 61, 62 .... and so on.

**Comment by muhammadAdeel6331** [comment]
I know that bro... and i already correct that..

**Comment by muhammadAdeel6331** [comment]
I know that bro... and i already corrected that....
